---
title: "Diamonds EDA"
author: "CT Ivan"
date: "May 18, 2017"
output: html_document
---

```{r setup, include=FALSE}
setwd("C:/Users/Christopher/Desktop/Nanodegree/P4-EDA")
knitr::opts_chunk$set(echo = TRUE)
library(dplyr, tidyr)
library(ggplot2)
```

```{r price vs x}
ggplot(aes(x = price, y = x), data=diamonds) +
  geom_point()
```

```{r correlating price and x}
cor.test(diamonds$price, diamonds$x)
cor.test(diamonds$price, diamonds$y)
cor.test(diamonds$price, diamonds$z)
```


```{r}
ggplot(aes(x = depth, y = price), data=diamonds) +
  geom_point(alpha=.05) +
  xlim(c(58,65))

cor.test(diamonds$price, diamonds$depth)
```

```{r price vs carat top 90%}
ggplot(aes(x = carat, y = price), 
       data=subset(diamonds, price < quantile(price, .99) 
                   & carat < quantile(price, .99))) +
  geom_point(alpha=.05)
```
```{r Volume field}
diamonds$volume = diamonds$x*diamonds$y*diamonds$z

ggplot(aes(x = volume, y = price), data=diamonds) +
  geom_point(alpha=.01) +
  xlim(c(0, 500))


library(plyr)
count(diamonds$volume == 0) #yields 20 values
detach("package:plyr", unload=TRUE)

affordable = subset(diamonds, volume>0 & volume <= 800)
cor.test(affordable$volume, affordable$price)
```

```{r affordable with lm}
ggplot(aes(x = volume, y = price), data=affordable) +
  geom_point(alpha=.01) +
  xlim(c(0, 500)) +
  geom_smooth(method = "lm")
```
diamondsByClarity

# The data frame should contain the following
# variables in this order.

#       (1) mean_price
#       (2) median_price
#       (3) min_price
#       (4) max_price
#       (5) n
```{r by clarity}
diamondsByClarity <- diamonds %>% group_by(clarity) %>% 
  summarize(mean_price = mean(price), 
            median_price = median(price), 
            min_price = min(price),
            max_price = max(price),
            n = n())
```
```{r bar plots for color and clarity}
diamonds_by_clarity <- group_by(diamonds, clarity)
diamonds_mp_by_clarity <- summarise(diamonds_by_clarity, mean_price = mean(price))
p1 = ggplot(aes(x=clarity, y=mean_price), data=diamonds_mp_by_clarity) +
  geom_col()

diamonds_by_color <- group_by(diamonds, color)
diamonds_mp_by_color <- summarise(diamonds_by_color, mean_price = mean(price))
p2 = ggplot(aes(x=color, y = mean_price),data=diamonds_mp_by_color) +
  geom_col()
grid.arrange(p1, p2)
```


